---
x-build-common: &build-common
  build:
    context: .
    dockerfile: Dockerfile
    target: development

x-app-common: &app-common
  environment:
    CI: ${CI:-false}
    CHROME_URL: ws://chrome:3333/?token=CHROMIUMTESTTOKEN
  extra_hosts:
    - "host.docker.internal:host-gateway"
  image: ghcr.io/rails-capybara-browserless/web:development

  stdin_open: true
  tty: true
  entrypoint: script/docker-entrypoint-development.sh
  volumes:
    - .:/app
    - bundler:/bundler
    - node_modules:/app/node_modules

services:
  web:
    <<: [*build-common, *app-common]
    depends_on:
      - chrome
      # - postgres
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - "3000:3000"

  chrome:
    image: ghcr.io/browserless/chromium:v2.13.0
    # image: browserless/chrome
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 3333:3333
    volumes:
      - .:/app:cached # change it for your rails' container directory
    environment:
      PORT: 3333
      # https://docs.browserless.io/docs/docker.html#connection-timeout
      CONNECTION_TIMEOUT: 600000
      TOKEN: CHROMIUMTESTTOKEN

  # postgres:
  #   image: postgres:16.3
  #   environment:
  #     POSTGRES_USER: pguser
  #     POSTGRES_PASSWORD: pgpassword
  #   volumes:
  #     - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
  bundler:
  node_modules:
